### ISSUE TITLE
Open Modal on Item Component Click

### ISSUE THREAD

**Issue by evanugarte** [evanugarte/InventoryEcho#19]
When clicking on an item component in the item list, a modal should pop up with the corresponding data from MongoDB. 
In this modal, an edit button should exist, where clicking on it has the items fields become entered in text boxes, and no longer as just words in the modal.

**Additional:**
Upon clicking save, the item's data should either be updated or kept the same, if the values didn't change or the text box was left blank.

**Comment by alizand1992** [comment]
This issue is assigned to me (Ali Zand)

**Comment by evanugarte** [comment]
When searching for items by name in Inventory Mode, the app crashes, pointing to the bind statement on line 25
