### ISSUE TITLE
Improve Item Component In InventoryView

### ISSUE THREAD

**Issue by evanugarte** [evanugarte/InventoryEcho#20]
Items should be listed by name, and under them should be quanitity and sale price. The 'x' button should be moved to the left of the item instead.

Example:

Kirkland Water (25oz)
Quantity: 5
$0.50

**Comment by alizand1992** [comment]
This ticket is assigned to Ali Zand

**Comment by alizand1992** [comment]
Per conversation with @evanugarte the x will be moved to the modal so it is up to me to put it where I want.

**Comment by alizand1992** [comment]
https://github.com/evanugarte/InventoryEcho/pull/22
